
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import TopNav from "@/components/common/TopNav";
import Social from "@/components/common/Social";




export const metadata = {
  title: "HemsWaterPark",
  description: "Generated by Trackonweb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <div>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap"
            rel="stylesheet"
          />
        </div>
      </head>
      <body className="font-Roboto bg-slate-100">
        <TopNav />
        <Header />
        {/* <Social /> */}
        {children}
     
        <Footer />
      </body>
    </html>
  );
}
